export CC = arm-none-eabi-gcc
export LD = arm-none-eabi-ld
export OBJCOPY = arm-none-eabi-objcopy

all:
	make -e -C day-2
	make -e -C day-4
	make -e -C day-5
	make -e -C day-6
	make -e -C day-7
	make -e -C day-8

clean:
	make -e -C day-2 clean
	make -e -C day-4 clean
	make -e -C day-5 clean
	make -e -C day-6 clean
	make -e -C day-7 clean
	make -e -C day-8 clean
