#ifndef IRQ_H
#define IRQ_H

#include "Gba.h"

typedef enum _IRQTABLE {
  IRQTABLE_VBL,
  IRQTABLE_HBL,
  IRQTABLE_YTRIG,
  IRQTABLE_TM0,
  IRQTABLE_TM1,
  IRQTABLE_TM2,
  IRQTABLE_TM3,
  IRQTABLE_COMMS,
  IRQTABLE_DMA0,
  IRQTABLE_DMA1,
  IRQTABLE_DMA2,
  IRQTABLE_DMA3,
  IRQTABLE_KEY,
  IRQTABLE_CART,

  IRQTABLE_NUM

} IRQTABLE;

extern u32 IntrTable[IRQTABLE_NUM];

extern void IrqNull() IN_IWRAM;

#endif
